### ISSUE TITLE
我适配了我校的教务系统，能提交给你吗

### ISSUE THREAD

**Issue by Winter-is-comingXK** [XFY9326/Schedule#29]
如题

**Comment by XFY9326** [comment]
如果要提交代码的话，你先fork项目到自己的账户下，在develop分支进行修改，然后提交一个merge request到我的develop分支。我会检查你的代码内容并合并。如果只是想自己发行魔改版的话，遵守GPL协议就好了。当然如果使用JS的适配方案就不需要询问我的意见了，直接分享你的配置文件链接给需要的人就好。

**Comment by XFY9326** [comment]
我也写了新的[适配指南](https://github.com/XFY9326/Schedule/wiki/00.%E4%BB%A3%E7%A0%81%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97)在wiki可供参考
