### ISSUE TITLE
课程时间冲突问题

### ISSUE THREAD

**Issue by Winter-is-comingXK** [XFY9326/Schedule#31]
有些课程的时间会产生冲突，例如 重修的课程、选课的课程都有可能造成时间冲突

**Comment by XFY9326** [comment]
在课程时间冲突这方面，我的设计要求是数据库不允许存放同一个课表有任何冲突的课程，并且尽量保证课程导入的完整性。因此如果出现时间冲突的问题会弹出提示，要求用户在开启“允许跳过部分无法导入的课程”功能后才能导入。开启这个功能后这部分冲突的课程时间将不会导入，只会导入课程基础信息与不冲突的时间信息，让用户自己处理。

**Comment by XFY9326** [comment]
为了实现这部分功能，可以看“CourseParseResult”以及“错误捕捉机制”的解释[wiki](https://github.com/XFY9326/Schedule/wiki/09.%E8%AF%BE%E7%A8%8B%E8%A7%A3%E6%9E%90%E5%B7%A5%E5%85%B7%E6%96%B9%E6%B3%95)。我看了你合并的代码，直接调用不含lambda函数的add方法是不会处理单个课程信息出错后跳过这个课程的操作的，需要使用CourseParseResult.Builder提供的错误捕捉的其他方法来提供这个功能。
