### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ccxx777** [XFY9326/Schedule#52]
南京审计大学导入课程之后，在设置课程单元格格式以后特别容易崩溃，不止一个学生有反馈，再次导入则直接崩溃，只能清楚软件数据再进入，进入以后依然是这个循环

**Comment by XFY9326** [comment]
该问题已知晓，目前正在修复中，如果有详细的报错日志可以直接发上来

**Comment by XFY9326** [comment]
该问题已在v1.5.2中修复

**Comment by ccxx777** [comment]
感谢修复，会告知同学可以正常使用了。

逸雪飞扬 ***@***.***> 于 2023年9月4日周一 18:52写道：
