### ISSUE TITLE
你好有个问题想请教一下

### ISSUE THREAD

**Issue by LOVEgithub12** [XFY9326/Schedule#54]
你好，看了您的“一种老旧安卓电视通用Root与优化方案-以创维G7200_8H87为例”的教程已经成功把当贝桌面改成了主页，但默认输入法不知如何更改，设置里改成搜狗输入法后无法调用。不知道是不是和改主页一样要改配置文件，望大佬赐教

**Comment by XFY9326** [comment]
这个我也不清楚，得慢慢看系统配置文件了，只能自己试试
